name: PowerAuth
version: ${project.version}
main: com.pawanpoudel.powerauth.PowerAuth
api-version: 1.20
authors: [PawanPoudel]
description: A hybrid authentication plugin with Premium AutoLogin support.

commands:
  register:
    description: Register a new account
    usage: /register <password> <confirmPassword>
  login:
    description: Login to your account
    usage: /login <password>

permissions:
  powerauth.admin:
    description: Allows admin management of authentication
    default: op
