name: PowerAuth
version: ${project.version}
main: com.pawanpoudel.powerauth.PowerAuth
api-version: 1.20
authors: [PowerSan]
description: A hybrid authentication plugin with Premium AutoLogin support.

commands:
  register:
    description: Register a new account
    usage: /register <password> <confirmPassword>
  login:
    description: Login to your account
    usage: /login <password>
  powerauth:
    description: PowerAuth admin commands
    aliases: [pa]
    usage: /powerauth <subcommand>

permissions:
  powerauth.admin.*:
    description: All admin permissions
    default: op
    children:
      powerauth.admin.forcelogin: true
      powerauth.admin.changepassword: true
      powerauth.admin.unregister: true
      powerauth.admin.info: true
      powerauth.admin.reload: true
  powerauth.admin.forcelogin:
    description: Force login a player
    default: op
  powerauth.admin.changepassword:
    description: Change a player's password
    default: op
  powerauth.admin.unregister:
    description: Unregister a player
    default: op
  powerauth.admin.info:
    description: View player account info
    default: op
  powerauth.admin.reload:
    description: Reload plugin configuration
    default: op
